# ShortConnect ProGuard / R8 rules — generated by with-optimized-gradle plugin.
# Do not edit manually: changes are overwritten by expo prebuild.

-dontobfuscate
-allowaccessmodification

# ── React Native core ──
-keep class com.facebook.react.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }
-keep class com.facebook.react.bridge.** { *; }
-keep class com.facebook.react.module.** { *; }
-keep class com.facebook.react.uimanager.** { *; }
-keep class com.facebook.react.views.** { *; }
-keep class com.facebook.react.modules.** { *; }
-keep class com.facebook.react.devsupport.** { *; }
-keep class com.facebook.react.hermes.** { *; }
-keep class com.facebook.react.views.imagehelper.** { *; }

# ── Hermes JS engine ──
-keep class com.facebook.hermes.** { *; }
-keep class com.facebook.hermes.reactexecutor.** { *; }

# ── Community modules ──
-keep class com.swmansion.reanimated.** { *; }
-keep class com.swmansion.gesturehandler.** { *; }
-keep class com.swmansion.rnscreens.** { *; }
-keep class com.swmansion.worklets.** { *; }
-keep class com.horcrux.svg.** { *; }
-keep class com.reactnativecommunity.webview.** { *; }
-keep class com.reactnativecommunity.** { *; }
-keep class fr.greweb.** { *; }

# ── Expo modules ──
-keep class expo.modules.** { *; }
-keep class * extends expo.modules.kotlin.modules.Module { *; }
-keep class * extends expo.modules.kotlin.view.ExpoView { *; }
-keep class * extends expo.modules.core.BasePackage { *; }
-keep class * implements expo.modules.core.interfaces.Package { *; }

# ── AsyncStorage / DateTimePicker / SafeAreaContext ──
-keep class com.reactnativecommunity.asyncstorage.** { *; }
-keep class com.reactcommunity.rndatetimepicker.** { *; }
-keep class com.th3rdwave.safeareacontext.** { *; }

# ── Native module interfaces ──
-keep class * implements com.facebook.react.bridge.NativeModule { *; }
-keep class * implements com.facebook.react.bridge.JavaScriptModule { *; }
-keep class * implements com.facebook.react.turbomodule.coreTurboModule { *; }
-keep class * extends com.facebook.react.bridge.ReactContextBaseJavaModule { *; }
-keep class * extends com.facebook.react.bridge.BaseJavaModule { *; }

# ── @ReactModule annotation ──
-keep @interface com.facebook.react.module.annotations.ReactModule { *; }
-keep @com.facebook.react.module.annotations.ReactModule class * { *; }
-keepclassmembers @com.facebook.react.module.annotations.ReactModule class * { *; }

# ── Application class ──
-keep class com.snapconnect.app.** { *; }
-keep class com.snapconnect.app.MainApplication { *; }
-keep class com.snapconnect.app.MainActivity { *; }

# ── Kotlin metadata ──
-keep class kotlin.Metadata { *; }
-keepclassmembers class ** { @kotlin.Metadata *; }

# ── OkHttp / network stack ──
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-keep class okio.** { *; }
-keep class javax.annotation.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**

# ── Google / AndroidX ──
-keep class com.google.android.gms.** { *; }
-keep class androidx.work.** { *; }
-keep class androidx.core.** { *; }
-dontwarn com.google.android.gms.**
-dontwarn androidx.work.**

# ── Enums and annotations ──
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
-keepattributes Signature
-keepattributes *Annotation*
-keepattributes EnclosingMethod
-keepattributes InnerClasses
-keepattributes RuntimeVisibleAnnotations
-keepattributes RuntimeInvisibleAnnotations

# ── JNI methods ──
-keepclasseswithmembernames class * {
    native <methods>;
}

# ── Package classes (autolinking) ──
-keep class **.**Package { *; }
-keep class * implements com.facebook.react.ReactPackage { *; }

# ── Suppress warnings ──
-dontwarn com.facebook.react.**
-dontwarn expo.modules.**
-dontwarn com.swmansion.**
-dontwarn com.horcrux.**
-dontwarn com.th3rdwave.**
-dontwarn com.reactnativecommunity.**
-dontwarn com.reactcommunity.**
-dontwarn fr.greweb.**
